landing:
    path: /home
    controller: App\Controller\LandingController::show
    methods: GET|HEAD

login:
    path: /login
    controller: App\Controller\LoginController::index
    methods: GET|POST

logout:
    path: /logout
    methods: GET

submit_login:
    path: api/login
    controller: App\Controller\LoginController::submitLoginForm
    methods: POST

registration:
    path: /register
    controller: App\Controller\RegistrationController::show
    methods: GET

submit_registration:
    path: api/register
    controller: App\Controller\RegistrationController::submitRegistrationForm
    methods: POST

root:
    path: /root
    controller: App\Controller\LandingController::showRoot
    methods: GET

list_expenses:
    path: /expenses
    controller: App\Controller\ExpenseController::show
    methods: GET|HEAD

create_expense:
    path: api/expenses/new
    controller: App\Controller\ExpenseController::create
    methods: POST

household_landing:
    path: /my-household
    controller: App\Controller\HouseholdController::show
    methods: GET|HEAD

create_household:
    path: api/my-household/new
    controller: App\Controller\HouseholdController::createNew
    methods: POST